source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XCTUIBridge_Example', :exclusive => true do
  pod "XCTUIBridge", :path => "../"
end

target 'XCTUIBridge_Tests', :exclusive => true do
  pod "XCTUIBridge", :path => "../"
end

target 'XCTUIBridge_ExampleUITests', :exclusive => true do
  pod 'XCTUIBridge', :path => "../"
end
